# MQTT unverschlüsselt (Auth erforderlich)
listener 1883
protocol mqtt
allow_anonymous false

# MQTT mit TLS (Auth erforderlich)
listener 8883
protocol mqtt
allow_anonymous false
cafile /mosquitto/certs/live/mqtt.ob5.dev/chain.pem
certfile /mosquitto/certs/live/mqtt.ob5.dev/cert.pem
keyfile /mosquitto/certs/live/mqtt.ob5.dev/privkey.pem
tls_version tlsv1.2

# WebSocket (Auth erforderlich)
listener 9001
protocol websockets
allow_anonymous false

# Authentifizierung
password_file /mosquitto/config/passwords.txt
acl_file /mosquitto/config/acl.txt

# Logging
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
